title: GitHub Test Website
author: Hamasak1
email: insert-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  test website to see what is possible, this description should be shown in a google
  search for this website. links should work in this description too (https://github.com/Hamasak1)

# social links
twitter_username: insert-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  insert-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-cayman
